name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: asdf_install
      uses: asdf-vm/actions/install@v1
    - name: Restore dependencies
      run: (cd src && dotnet restore)
    - name: Build Cli
      # We have to build the CLI first otherwise our example will fail to build
      run: (cd src/Bottlecap.Net.GraphQL.Generation.Cli && dotnet build --no-restore)
    - name: Build Rest
      run: (cd src/Bottlecap.Net.GraphQL.Generation.Cli && dotnet build --no-restore)
